POST http://localhost:8000/api/execute
Content-Type: application/json

{
  "task": "기업은행 지난주 거래 내역 "
}


### Few-shot 데이터 추가
POST http://localhost:8000/data/upload
Content-Type: application/json

{
  "collection_name": "example_collection",
  "item_id": "1",
  "text": "This is a test text",
  "type": "C",
  "del_yn": "N"
}

### Few-shot 데이터 업데이트
PUT http://localhost:8000/data/update
Content-Type: application/json

{
  "collection_name": "example_collection",
  "item_id": "1",
  "text": "This is an updated t2est text1111",
  "type": "C",
  "del_yn": "N"
}

### Few-shot 데이터 삭제
DELETE http://localhost:8000/data/delete
Content-Type: application/json

{
  "collection_name": "example_collection",
  "item_id": "1",
  "text": "This is a test text",
  "type": "C",
  "del_yn": "Y"
}

### PostgreSQL 데이터 조회
POST http://localhost:8000/data/get/postgresql
Content-Type: application/json

{
  "collection_name": "example_collection",
  "item_id": "1",
  "text": "This is a test text",
  "type": "C",
  "del_yn": "N"
}


### 새 Prompt 데이터 추가
POST http://localhost:8000/data/prompt/add
Content-Type: application/json

{
  "prompt_name": "example_prompt",
  "prompt": "This is an example prompt"
}

### Prompt 데이터 조회
GET http://localhost:8000/data/prompt/get/solver_json_schema_part
Content-Type: application/json