# Test your FastAPI endpoints

POST http://127.0.0.1:8000/api/test
Content-Type: application/json

{
    "user_input": "거래처 이름이 '삼성전자'인 거래 중 1억 원 이상 거래된 건수를 확인해줘"
}

###

POST http://172.19.200.201:8000/api/test
Content-Type: application/json

{
    "user_input": "거래처 이름이 '삼성전자'인 거래 중 1억 원 이상 거래된 건수를 확인해줘"
}