server:
    port: 8000
    address: 0.0.0.0
    servlet:
        context-path: /

    tomcat:
        threads:
          max: 200
          min-spare: 25
        max-connections: 8192
        accept-count: 100
        connection-timeout: 20000

spring:
    config:
        activate:
            on-profile: dev
    jackson:
        time-zone: Asia/Seoul
        date-format: yyyy-MM-dd HH:mm:ss
        serialization:
            write-dates-as-timestamps: false
            write-date-timestamps-as-nanoseconds: false

    # prompt db
    datasource:
        url: jdbc:postgresql://172.27.111.18:54313/cboarddevdb
        username: cboarddev
        password: cboarddev123
        driver-class-name: org.postgresql.Driver
        hikari:
            schema: aicfoagentdev

            maximum-pool-size: 30      # 최대 커넥션 수
            minimum-idle: 10           # 최소 유휴 커넥션
            connection-timeout: 30000  # 30초
            idle-timeout: 600000       # 10분
            max-lifetime: 1800000      # 30분
            leak-detection-threshold: 60000  # 1분

    jpa:
        hibernate:
            ddl-auto: validate
        show-sql: false
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQL10Dialect
                format_sql: true
                default_schema: aicfoagentdev
                use_sql_comments: true
                jdbc:
                    lob:
                        non_contextual_creation: true

# finance db
db:
    url: jdbc:postgresql://172.27.111.18:54313/cboarddevdb
    username: cboarddev
    password: cboarddev123
    driver-class-name: org.postgresql.Driver
    hikari:
        schema: cboarddev

        maximum-pool-size: 20
        minimum-idle: 5
        connection-timeout: 30000
        idle-timeout: 600000

system:
    expire:
        date: 21251211
    company:
        id: aicfo_dev

jwt:
    secret: uI9xvH1zMf+jrD9PbCkA2JGz0r3YVx/EoMdiZtJd2+E
    expiration: 86400000 # 24시간

# FLOW API 설정
flow:
    project:
        id: 2605967
    api:
        key: 20240903104057549-a1b44794-1dc5-42e4-9098-36939ab89144
        url: https://api.flow.team/v1/bots/daquv@daquv.com/notifications
    register:
        email: hajkim@daquv.com

admin:
    email: anriver@daquv.com

# API 설정
api:
    url: http://121.78.125.134:8000/v1/chat/completions
    vector-store-domain: http://211.233.64.101:8000
    quvi-base-url: http://localhost:8099
    quvi-column: ${api.quvi-base-url}/column
    quvi-query: ${api.quvi-base-url}/query
    quvi-fstring: ${api.quvi-base-url}/fstring/compute_fstring

llm:
    base-url: http://121.78.125.134:8000

# 로깅 설정
logging:
    level:
        com.daquv: INFO
        org.springframework.web: INFO
        org.hibernate.SQL: INFO
        org.hibernate.type.descriptor.sql.BasicBinder: INFO

profiling:
    enabled: false
