spring:
  profiles:
    default: daquv
  jackson:
    time-zone: Asia/Seoul
    date-format: yyyy-MM-dd HH:mm:ss
    serialization:
      write-dates-as-timestamps: false
      write-date-timestamps-as-nanoseconds: false

jwt:
  secret: uI9xvH1zMf+jrD9PbCkA2JGz0r3YVx/EoMdiZtJd2+E
  expiration: 86400000 # 24시간

system:
  expire:
    date: 21251211
  company:
    id: aicfo

view-table:
  dialect: postgres
  view-func: aicfo_get_all_

api:
  quvi-base-url: http://localhost:8099
  quvi-column: ${api.quvi-base-url}/column
  quvi-query: ${api.quvi-base-url}/query
  quvi-fstring: ${api.quvi-base-url}/fstring/compute_fstring

# 띄어쓰기 없는 쉼표로 구분하여 여러 엔티티 설정
semantic:
  entities: bal, trsc

app:
  filesystem-base-path: /home/daquv/src/qv_aicfo/agent/src/main/resources

